Ensure 'scipy'>1.1.0 due to ImportError
ImportError: cannot import name find_peaks

REF:
        https://stackoverflow.com/a/53000194/4521950

	modified:   requirements.txt